<?php
declare(strict_types=1);

namespace TimeTracker;

/**
 * Reads config/config.php (generated by the setup page). The file lives outside the web root.
 */
final class Config
{
    private static ?array $data = null;

    public static function path(): string
    {
        return TT_ROOT . '/config/config.php';
    }

    public static function isInstalled(): bool
    {
        return is_file(self::path());
    }

    public static function all(): array
    {
        if (self::$data === null) {
            self::$data = self::isInstalled() ? (array) (require self::path()) : [];
        }
        return self::$data;
    }

    /** Dotted lookup: Config::get('db.host'). */
    public static function get(string $key, mixed $default = null): mixed
    {
        $value = self::all();
        foreach (explode('.', $key) as $part) {
            if (!is_array($value) || !array_key_exists($part, $value)) {
                return $default;
            }
            $value = $value[$part];
        }
        return $value;
    }

    /** PHP source for a config file. */
    public static function render(array $db, string $timezone): string
    {
        $data = [
            'db'  => [
                'host' => $db['host'],
                'port' => (int) $db['port'],
                'name' => $db['name'],
                'user' => $db['user'],
                'pass' => $db['pass'],
            ],
            'app' => [
                'timezone'     => $timezone,
                'debug'        => false,
                'installed_at' => date('c'),
                'version'      => TT_VERSION,
            ],
        ];
        return "<?php\n// Generated by the Timetracker setup page. Keep this file private.\nreturn "
            . var_export($data, true) . ";\n";
    }
}
